### ISSUE TITLE
stats: FSL doesn't write my papers for me.

### ISSUE THREAD

**Issue by nicholst** [FMRIB-Software-Library/support#10]
## Checklist 

- I have checked that this issue or question has not already been [reported on this issue tracker](https://github.com/FMRIB-Software-Library/fsl-issues-and-support/issues?q=) 
- FSL version:       6.0.3 
- Operating system:   Darwin CausticJelly.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Jan 12 22:04:47 PST 2021; root:xnu-4903.278.56~1/RELEASE_X86_64 x86_64
---

#### Describe the problem

I analyze my data, but I find that I'm then left to interpret and write up the results as a paper.

#### 

```
feat design.fsf
```

#### 

Can FSL please have a natural language module that will review my outputs and produce the methods and results section and, if possible, the introduction and discussion too?

**Comment by hanayik** [comment]
This seems to be the solution: https://storyai.botsociety.io/

**Comment by nicholst** [comment]
Thanks for the suggestion @hanayik !  I've pasted in my FEAT output into the StoryBot and I'll see what it produces.
